spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  #    url: jdbc:mysql://localhost:3306/mptest?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatementshedStatements=true&allowMultiQueries=true
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    username: C##root
    password: 123456
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      #validation-query: select 'x'
      validation-query: select 1 from dual
      stat-view-servlet:
        allow: ''
        deny: ''
        enabled: true
        login-username: admin
        login-password: ENC(aTtkWaNYFlov2jHLO4aFVQ==)
        reset-enable: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
        url-pattern: /*

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:

    db-config:
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    #主键类型  0:"数据库ID自增",1:为空, 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
      id-type: INPUT